CarDealer/CarDelaer.Web/Controllers/CarsController.cs
namespace CarDealer.Web.Controllers
{
    using CarDealer.Data.Models.Enums;
    using CarDealer.Services;
    using CarDealer.Web.Models.Cars;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Collections.Generic;
    using System.Linq;

    [Route("cars")]
    public class CarsController : Controller
    {
        private const string RedirectToLogin = "/account/login";

        private readonly ICarService cars;
        private readonly IPartService parts;
        private readonly ILogService logs;

        public CarsController(
            ICarService cars,
            IPartService parts,
            ILogService logs)
        {
            this.cars = cars;
            this.parts = parts;
            this.logs = logs;
        }

        [Route("all")]
        public IActionResult All()
        {
            return View(this.cars.AllListing());
        }

        [Route("{make}")]
        public IActionResult ByMake(string make)
        {
            var allCars = this.cars.ByMake(make);

            return View(new CarsByMakeModel
            {
                Make = make,
                Cars = allCars
            });
        }

        [Route("parts")]
        public IActionResult Parts()
        {
            return View(this.cars.CarWithParts());
        }

        [Authorize]
        [Route(nameof(Create))]
        public IActionResult Create()
        {
            return View(new CarFormModel { Parts = this.GetPartsListItems() });
        }

        [Authorize]
        [HttpPost]
        [Route(nameof(Create))]
        public IActionResult Create(CarFormModel carModel)
        {
            if (!ModelState.IsValid)
            {
                carModel.Parts = this.GetPartsListItems();
                return View(carModel);
            }

            this.cars.Create(
                carModel.Make,
                carModel.Model,
                carModel.TravelledDistance,
                carModel.SelectedParts);

            this.logs.Create(User.Identity.Name, "Car", Operation.Add);

            return RedirectToAction(nameof(All));
        }

        private IEnumerable<SelectListItem> GetPartsListItems()
            => this.parts.All()
                .Select(p => new SelectListItem
                {
                    Text = p.Name,
                    Value = p.Id.ToString()
                });
    }
}

CarDealer/CarDelaer.Web/Controllers/LogsController.cs
namespace CarDealer.Web.Controllers
{
    using CarDealer.Services;
    using CarDealer.Web.Models.Logs;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Linq;

    public class LogsController : Controller
    {
        private const int PageSize = 10;

        private readonly ILogService logs;

        public LogsController(ILogService logs)
        {
            this.logs = logs;
        }

        public IActionResult All(string searchTerm, int page = 1)
        {
            var logs = this.logs.AllListing(searchTerm, page, PageSize);

            return View(new LogPageListingModel
            {
                Logs = logs,
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(this.logs.Total(searchTerm) / (double)PageSize),
                SearchTerm = searchTerm
            });
        }

        public IActionResult Clear()
        {
            this.logs.ClearLogs();

            return RedirectToAction(nameof(All));
        }
    }
}

CarDealer/CarDelaer.Web/Controllers/PartsController.cs
namespace CarDealer.Web.Controllers
{
    using CarDealer.Services;
    using CarDealer.Web.Models.Parts;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public class PartsController : Controller
    {
        private const int PageSize = 25;

        private readonly IPartService parts;
        private readonly ISupplierService suppliers;

        public PartsController(
            IPartService parts,
            ISupplierService suppliers)
        {
            this.parts = parts;
            this.suppliers = suppliers;
        }

        public IActionResult All(int page = 1)
        {
            var parts = this.parts.AllListing(page);

            return View(new PartPageListingModel
            {
                Parts = this.parts.AllListing(page, PageSize),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(this.parts.Total() / (double)PageSize)
            });
        }

        public IActionResult Create()
            => View(new PartFormModel
            {
                Suppliers = this.GetSuppliersListItems()
            });

        [HttpPost]
        public IActionResult Create(PartFormModel partModel)
        {
            if (!ModelState.IsValid)
            {
                partModel.Suppliers = this.GetSuppliersListItems();
                return View(partModel);
            }

            this.parts.Create(partModel.Name, partModel.Price, partModel.Quantity, partModel.SupplierId);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Edit(int id)
        {
            var currentPart = this.parts.ById(id);

            if (currentPart == null)
            {
                return NotFound();
            }

            return View(new PartFormModel
            {
                Name = currentPart.Name,
                Price = currentPart.Price,
                Quantity = currentPart.Quantity,
                IsEdit = true
            });
        }

        [HttpPost]
        public IActionResult Edit(int id, PartFormModel partForm)
        {
            if (!ModelState.IsValid)
            {
                partForm.IsEdit = true;
                return View(partForm);
            }

            this.parts.Edit(
                    id,
                    partForm.Price,
                    partForm.Quantity);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Delete(int id)
        {
            if (!this.parts.Exist(id))
            {
                return NotFound();
            }

            var currentPart = this.parts.ById(id);
            if (currentPart == null)
            {
                return NotFound();
            }

            return View(currentPart);
        }

        public IActionResult ConfirmDelete(int id)
        {
            if (!this.parts.Exist(id))
            {
                return NotFound();
            }

            this.parts.Delete(id);

            return RedirectToAction(nameof(All));
        }

        private IEnumerable<SelectListItem> GetSuppliersListItems()
            => this.suppliers.All()
                .Select(s => new SelectListItem
                {
                    Text = s.Name,
                    Value = s.Id.ToString()
                });
    }
}

CarDealer/CarDelaer.Web/Controllers/SalesController.cs
namespace CarDealer.Web.Controllers
{
    using CarDealer.Data.Models.Enums;
    using CarDealer.Services;
    using CarDealer.Web.Models.Sales;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Collections.Generic;
    using System.Linq;

    [Route("sales")]
    public class SalesController : Controller
    {
        private readonly ISaleService sales;
        private readonly ICarService cars;
        private readonly ICustomerService customers;
        private readonly ILogService logs;

        public SalesController(
            ISaleService sales,
            ICarService cars,
            ICustomerService customers,
            ILogService logs)
        {
            this.sales = sales;
            this.cars = cars;
            this.customers = customers;
            this.logs = logs;
        }

        public IActionResult All()
        {
            return View(this.sales.All(false, null));
        }

        [Route("{id}")]
        public IActionResult Details(int id)
        {
            return View(this.sales.ById(id));
        }

        [Route("discounted")]
        public IActionResult Discounted()
        {

            return View(this.sales.All(true, null));
        }

        [Route("discounted/{percent}")]
        public IActionResult Discounted(double percent)
        {
            return View(this.sales.All(true, percent));
        }

        [Authorize]
        [Route("create")]
        public IActionResult Create()
        {
            return View(new CreateSaleFormModel
            {
                Customers = this.GetCustomersListItems(),
                Cars = this.GetCarsListItems()
            });
        }

        [Authorize]
        [Route("ConfirmCreate")]
        public IActionResult ConfirmCreate(CreateSaleFormModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Customers = this.GetCustomersListItems();
                model.Cars = this.GetCarsListItems();
                return View(nameof(Create), model);
            }

            var customer = this.customers.ById(model.CustomerId);
            var car = this.cars.ById(model.CarId);
            double discount = ((customer.IsYoungDriver == true ? 5 : 0) + model.Discount) / 100;

            return View(new CreateSaleConfirmFormModel
            {
                CarId = model.CarId,
                CustomerId = model.CustomerId,
                Discount = discount * 100,
                CarName = car.CarName,
                CustomerName = customer.Name,
                Price = car.Price,
                FinalPrice = car.Price - (car.Price * (decimal)discount)
            });
        }

        [Authorize]
        [HttpPost]
        [Route("ConfirmCreate")]
        public IActionResult ConfirmCreate(CreateSaleConfirmFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Create));
            }

            this.sales.Create(model.CustomerId, model.CarId, model.Discount);
            this.logs.Create(User.Identity.Name, "Sale", Operation.Add);

            return RedirectToAction(nameof(All));
        }

        private IEnumerable<SelectListItem> GetCustomersListItems()
            => this.customers.All().Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });

        private IEnumerable<SelectListItem> GetCarsListItems()
            => this.cars.All()
                .Select(c => new SelectListItem
                {
                    Text = $"{c.Make} - {c.Model}",
                    Value = c.Id.ToString()
                });
    }
}

CarDealer/CarDelaer.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car Delaer</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Car Dealer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Customers <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/customers/all/ascending">All</a></li>
                            <li><a asp-area="" asp-controller="Customers" asp-action="Create">Create</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" >Sales <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Sales" asp-action="All">All</a></li>
                            <li><a asp-area="" asp-controller="Sales" asp-action="Discounted">Discounted</a></li>
                            <li><a asp-controller="Sales" asp-action="Create">Create</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Cars <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Cars" asp-action="All">All</a></li>
                            <li><a asp-area="" asp-controller="Cars" asp-action="Create">Create</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Parts" asp-action="All">Parts</a></li>
                    <li><a asp-area="" asp-controller="Suppliers" asp-action="All">Suppliers</a></li>
                    <li><a asp-area="" asp-controller="Logs" asp-action="All">Logs</a></li>
                    
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Car Dealer</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>